# $schema: https://json.schemastore.org/dependabot-2.0.json

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/nextjs-interface" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "composer"
    directory: "/php"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
