# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - "./data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: memoires-info

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080

  postg-rest:
    image: postgrest/postgrest
    restart: always
    ports:
      - "3000:3000"
    environment:
      # this is the equivalent to the postgrest.conf file
      PGRST_DB_SCHEMAS: "api"
      PGRST_DB_ANON_ROLE: "web_anon"
      PGRST_DB_URI: postgres://postgres:example@db:5432/memoires-info
      PGRST_JWT_SECRET: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      PGRST_OPENAPI_SERVER_PROXY_URI: http://0.0.0.0:3000
    depends_on:
      - db

  esphome:
    image: esphome/esphome
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: always
    privileged: true
    network_mode: host
